config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  
  resources :categories, only: %i[index show new create] do
    resources :payments, only: %i[index new create]
  end

  root to: 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :category_payments
  has_many :payments, through: :category_payments
  has_one_attached :icon

  validates :name, presence: true, uniqueness: true
  validates :icon, presence: true

  def total_payments
    payments.sum(:amount)
  end
end

app/models/category_payment.rb
class CategoryPayment < ApplicationRecord
  belongs_to :category
  belongs_to :payment
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :category_payments
  has_many :categories, through: :category_payments

  validates :name, presence: true
  validates :amount, presence: true, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, foreign_key: :author_id
  has_many :payments, foreign_key: :author_id
  has_one_attached :avatar

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :password)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = current_user.categories.build(categories_params)

    if @category.save
      redirect_to categories_path, notice: 'Category created successfully'
    else
      render :new, alert: 'Failed to create payment.'
    end
  end

  private

  def categories_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @category = Category.includes(:payments).find(params[:category_id])
    @payments = @category.payments.order(created_at: :desc)
  end

  def new
    @category = Category.find(params[:category_id])
    @payment = Payment.new
    @categories = current_user.categories
  end

  def create
    @category = Category.find(params[:payment][:category_id])
    @payment = @category.payments.build(payments_params)
    @payment.author = current_user

    if @payment.save
      CategoryPayment.create(category: @category, payment: @payment)
      redirect_to category_payments_path(@category), notice: 'Payment created successfully'
    else
      render :new, alert: 'Failed to create payment.'
    end
  end

  private

  def payments_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :avatar)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div class="flex flex-col gap-4 px-8 mt-2">
  <% @categories.each do |category| %>
    <%= link_to category_payments_path(category), class: 'category_link' do %>
      <div class="p-4 flex justify-between items-center bg-slate-200 hover:bg-blue-200">
        <div class="flex gap-4 items-center">
          <%= image_tag(category.icon, class: "h-16 w-16") if category.icon.attached? %>
          <h2 class="text-xl font-medium"><%= category.name.upcase %></h2>
        </div>
        <p class="text-red-700">$<%= category.total_payments %></p>
      </div>
    <% end %>
  <% end %>
</div>

<footer class="fixed bottom-0 flex justify-center w-full">
  <button class="w-full bg-emerald-400 hover:bg-emerald-600 p-4 text-white text-xl font-medium">
    <%= link_to 'ADD NEW CATEGORY', new_category_path %>
  </button>
</footer>

app/views/categories/new.html.erb
<div class="flex items-center justify-center w-full bg-blue-200 p-4">
   <h2 class="text-md text-slate-500 font-medium">ADD NEW CATEGORY</h2>
</div>

<div class="flex flex-col gap-4 px-8">
  <%= form_with(model: @category, url: categories_path, method: :post, class: '') do |form| %>
     <div class="mt-2">
       <%= form.text_field :name, placeholder: 'Name', required: true, class: 'w-full' %>
     <div>
     <div class="mt-6 gap-2 flex flex-col">
       <%= form.label :icon %>
       <%= form.file_field :icon, class: "form-control w-full" %>
     </div>
     <button class="flex w-full items-center justify-center mt-10 p-4 bg-emerald-500 text-white font-medium hover:bg-emerald-600">
      <%= form.submit "SAVE", class: "cursor-pointer" %>
     </button>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Financier</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.css" rel="stylesheet" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col w-full">
    <% if user_signed_in? %>
      <nav>
        <div class="flex items-center justify-between w-full bg-blue-500 p-4">
          <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" type="button" data-drawer-target="drawer-navigation" data-drawer-show="drawer-navigation" aria-controls="drawer-navigation">
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
               <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
            </svg>
          </button>
          <p class="text-white text-2xl font-medium"><%= controller_name.upcase %></p>
          <%= button_to "SIGN OUT", destroy_user_session_path, method: :delete, class: "ml-4 bg-white text-black p-2 rounded-md hover:bg-red-400" %>
        </div>
    
        <!-- drawer component -->
        <div id="drawer-navigation" class="fixed top-0 left-0 z-40 w-64 h-screen p-4 overflow-y-auto transition-transform -translate-x-full bg-white dark:bg-gray-800" tabindex="-1" aria-labelledby="drawer-navigation-label">
            <h5 id="drawer-navigation-label" class="text-base font-semibold text-gray-500 uppercase dark:text-gray-400">MENU</h5>
            <button type="button" data-drawer-hide="drawer-navigation" aria-controls="drawer-navigation" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 absolute top-2.5 right-2.5 inline-flex items-center dark:hover:bg-gray-600 dark:hover:text-white" >
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                <span class="sr-only">CLOSE MENU</span>
            </button>
            <div class="py-4 overflow-y-auto">
               <div class="flex items-center gap-x-4 mt-2">
                 <% if user_signed_in? %>
                   <%= image_tag(current_user.avatar, class: "rounded-full h-12 w-12") if current_user.avatar.attached? %>
                   <p class="text-gray-900 dark:text-white italic"><%= current_user.name.upcase %></p>
                 <% end %>
               </div>
                <ul class="space-y-2 mt-10 font-medium">
                   <li>
                      <a href="<%= root_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                         <svg class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
                            <path d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"/>
                            <path d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"/>
                         </svg>
                         <span class="ml-3">CATEGORIES</span>
                      </a>
                   </li>
                   <li>
                      <a href="<%= new_category_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                         <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 20">
                            <path d="M17 5.923A1 1 0 0 0 16 5h-3V4a4 4 0 1 0-8 0v1H2a1 1 0 0 0-1 .923L.086 17.846A2 2 0 0 0 2.08 20h13.84a2 2 0 0 0 1.994-2.153L17 5.923ZM7 9a1 1 0 0 1-2 0V7h2v2Zm0-5a2 2 0 1 1 4 0v1H7V4Zm6 5a1 1 0 1 1-2 0V7h2v2Z"/>
                         </svg>
                         <span class="flex-1 ml-3 whitespace-nowrap">ADD NEW CATEGORY</span>
                      </a>
                   </li>
                   <li>
                      <div class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
                         <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 16">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 8h11m0 0L8 4m4 4-4 4m4-11h3a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-3"/>
                         </svg>
                         <%= button_to "LOG OUT", destroy_user_session_path, method: :delete, class: "ml-3" %>
                      </div>
                    </li>
                </ul>
             </div>
        </div>
      </nav>
    <% end %>

    <div class="flex flex-col items-center justify-center">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>

    <%= yield %>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.7.0/flowbite.min.js"></script>

  </body>
</html>

app/views/payments/index.html.erb
<div class="flex justify-between p-4 font-medium bg-slate-200">
   <h2 class="">TOTAL PAYMENTS</h2>
   <p class="text-red-700">$<%= @category.total_payments %></p>
</div>

<div id="foods" class="min-w-full flex flex-col items-center justify-center mt-4 px-8">
    <table class="min-w-full border">
      <thead>
        <tr>
          <th class="px-6 py-3 bg-gray-200 text-gray-700 border-b">Name</th>
          <th class="px-6 py-3 bg-gray-200 text-gray-700 border-b">Amount</th>
        </tr>
      </thead>
      <tbody>
        <% @payments.each do |payment| %>
          <tr>
            <td class="ml-2 px-6 py-4 border border-gray-200"><%= payment.name %></td>
            <td class="ml-2 px-6 py-4 border border-gray-200 text-red-700">$<%= payment.amount %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

<button class="fixed bottom-0 w-full bg-emerald-500 p-4 text-white font-medium text-xl">
    <%= link_to 'ADD NEW PAYMENT', new_category_payment_path, class: 'add-new-link'  %>
</button>


app/views/payments/new.html.erb
<div class="flex items-center justify-center w-full bg-blue-200 p-4">
   <h2 class="text-md text-slate-500 font-medium">ADD NEW PAYMENTS</h2>
</div>

<div class="flex flex-col w-full px-8">
  <%= form_with(model: @payment, url: category_payments_path, method: :post, class: 'add-new-form') do |form| %>
    <div class="mt-2">
      <%= form.text_field :name, placeholder: 'Name', required: true, class: 'w-full' %>
    </div>
    <div class="mt-2">
      <%= form.text_field :amount, placeholder: 'Amount', required: true, class: 'w-full' %>
    </div>
    <div class="mt-2">
      <%= form.collection_select :category_id, @categories, :id, :name, { include_blank: 'Select category' }, required: true, class: 'w-full'  %>
    </div>
    <button class="flex w-full items-center justify-center mt-10 p-4 bg-emerald-500 text-white font-medium hover:bg-emerald-600">
      <%= form.submit "SAVE", class: "cursor-pointer" %>
    </button>
  <% end %>
</div>

app/views/users/index.html.erb
<div class='flex flex-col h-screen items-center justify-center w-full py-8 pb-10'>
  <div class='flex flex-col items-center justify-center flex-grow'>
    <div class='app-logo'>
      <h1 class="text-6xl font-semibold italic mt-[20%] text-transparent bg-clip-text bg-gradient-to-r from-blue-400 via-pink-500 to-red-500">Financier</h1>
      <p class="ml-24 text-slate-700 italic">...the smart mobile solution</p>
    </div>
  </div>
  <div class='flex flex-col items-center w-full'>
    <div class='mb-4 w-full px-4'>
      <button class='p-4 bg-blue-500 hover:bg-emerald-400 w-full text-white'>
        <%= link_to 'LOG IN', new_user_session_url, class: 'login-link' %>
      </button>
    </div>
    <div>
      <button>
        <%= link_to 'SIGN UP', new_user_registration_url, class: 'signup-link' %>
      </button>
    </div>
  </div>
</div>